### ISSUE TITLE
Error when installing the custom component

### ISSUE THREAD

**Issue by taugusti** [jamiewalters/python-verisure-climate#1]
Hi Jamie,
I installed the files (and folders) in /config/custom_components
I inserted logininfo into /config/custom_components/verisureclimate.py
I inserted verisureclimate: in /config/configuration.yaml

During boot I get this:

Error during setup of component verisureclimate

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
AttributeError: module 'custom_components.verisureclimate' has no attribute 'setup'

Can you help me identify the issue?

**Comment by jamiewalters** [comment]
Does it look like this in the config?
<pre>climate:
  - platform: verisureclimate
</pre>

**Comment by taugusti** [comment]
That helped :-) It seems to work now - looking forward to test it over the next days!
And great that you updated the guide.
To make it easy for the next ones, meybe you could also add info that the verisureclimate.py and sub folders must be placed in /config/custom_components/climate
Great work thanks!
/th

**Comment by jamiewalters** [comment]
Thanks for the feedback, have updated this. Have also pushed a new version this morning. Please update with this.

**Comment by taugusti** [comment]
Great with the update - I was hoping you would do that so the component can be promoted to the hass system once it has been tested :-)

**Comment by taugusti** [comment]
A few questions / comments
- it seems like the temperatures have 0 decimals...? At least the measured temperature should have one decimal. I am pretty sure that it comes from verisure in that format... Hmm - just checked historical values - I might be wrong...
- How often does the component update? Right now the temp shows 28 in HASS and 26 in the verisure app..?

**Comment by taugusti** [comment]
Regarding the update - something must have been wrong during my previous tests - not it seeems that changes are reflected after approx 2 minutes.

**Comment by jamiewalters** [comment]
It is about 1-2 mins. Not sure how much more frequently it should be, trying to avoid too many calls to the server. I have added a new version, this sets the increment to steps of 1deg similar to the app.

**Comment by taugusti** [comment]
cool - I will try it
Still - already now this is great!
Going offline for a couple of days - I will get back to you next week.

**Comment by taugusti** [comment]
I was unable to update last night (time not technical) - and this morning the history graph shows that the data is not updated:
![image](https://user-images.githubusercontent.com/15052792/45735530-6f5d6a80-bbe8-11e8-8409-a7ff9d6136fc.png)

**Comment by jamiewalters** [comment]
Odd, how is it looking now

**Comment by taugusti** [comment]
Same - 26degC current temp totally unchanged from yesterday....
(I forgot to make a screenshot before I updated the component and rebooted)

Could it be the way I fetch the graph data? - I do it like this:
sensor:
  - platform: template
    sensors:
      hp_temperature:
        friendly_name: Living room temperature
        value_template: '{{ states.climate.stue.attributes.current_temperature }}'
        unit_of_measurement: '°C'
      hp_setpoint:
        friendly_name: Heat pump setpoint
        value_template: '{{ states.climate.stue.attributes.temperature }}'
        unit_of_measurement: '°C'

history_graph:
  gr1:
    name: Living room temperature
    entities:
      - sensor.hp_temperature
      - sensor.hp_setpoint
    hours_to_show: 1344
    refresh: 30

**Comment by taugusti** [comment]
Now it updated at restart - lets see in the morning
![image](https://user-images.githubusercontent.com/15052792/45778440-e6324c00-bc58-11e8-8c47-4fb3eab298af.png)

**Comment by jamiewalters** [comment]
Pushed a fix for this.

**Comment by taugusti** [comment]
seems to work - great - thanks! I will give you further feedback in a week or so.

![image](https://user-images.githubusercontent.com/15052792/45904714-1fe88b80-bdee-11e8-9557-fbdefdc7f7ec.png)

**Comment by jamiewalters** [comment]
Excellent
