### ISSUE TITLE
Component does not work after 0.96 update

### ISSUE THREAD

**Issue by mycortex** [jamiewalters/python-verisure-climate#10]
Maybe it has something to do with this?
https://developers.home-assistant.io/blog/2019/07/03/climate-cleanup.html

**Comment by taugusti** [comment]
Hi,
Sounds like a major refactoring must be made :-(
I do not have the time to research and do it at the moment. It will be another year before I complete my MBA and get the priveledge of spare time again...
I guess I will keep my system on 0.95 for the time beeing :-(

**Comment by mycortex** [comment]
fixed
