### ISSUE TITLE
Bleaking change 2021.6 - "version" missing in manifest.json

### ISSUE THREAD

**Issue by mycortex** [jamiewalters/python-verisure-climate#13]
This is now required in custom components.

I have fixed this locally be modifying the manifest.json-file to this:

{
"domain": "verisureclimate",
"name": "Verisureclimate",
"documentation": "https://github.com/jamiewalters/python-verisure-climate",
"dependencies": [],
"codeowners": [],
"requirements": [],
"version": "1.0.0"
}

**Comment by mycortex** [comment]
I've made a pull request from my repo to fix this.
If it's not merged you can use the files in mye repo:
[https://github.com/mycortex/python-verisure-climate](https://github.com/mycortex/python-verisure-climate)
Working in HA 2021.6

**Comment by jamiewalters** [comment]
Merged.
