### ISSUE TITLE
Not working as a stand-alone component

### ISSUE THREAD

**Issue by stefsims** [jamiewalters/python-verisure-climate#2]
I tried to install this component without python-verisure (https://github.com/persandstrom/python-verisure) and it didn't work.
Worked perfect after installing python-verisure.

**Comment by jamiewalters** [comment]
Interesting, I'll take a look at this.

**Comment by jamiewalters** [comment]
Of course if you are running python verisure then you wont need the embedded files as it has the 1.5. The added files are geared towards HASS with verisure component installed, it uses only 1.3
